# Generated by Django 4.0.2 on 2022-02-11 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 23, 26, 0, 149902)),
        ),
    ]
